### PR TITLE
Added most module arguments of tower_job_template and added ask inventory/vars for CRD

### LINKED ISSUE #47: [RFE] Add prompt on launch for extra vars and inventory
Add option to CRD for prompt on launch for extra vars and inventory.  Required for use with ACM.

### PR DESCRIPTION
**Pull request by davidtluong**
Added field for ask extra vars/inventory on launch 
Added most of the module args for job_templates that made sense for the roles so that users can still use the arguments by putting into the yaml manually
Resolves #47

### CODE REVIEW

**Review by matburt — APPROVED** [review]
lgtm

**Comment by davidtluong** [comment]
Anything else I need to do? I see it's waiting on review from @shanemcd and @Spredzy

**Comment by matburt** [comment]
This has a conflict, so you'll need to rebase it at least.

**Comment by davidtluong** [comment]
@matburt Done

**Comment by davidtluong** [comment]
So, after seeing that I needed to rebase again cause deploy/crds/tower.ansible.com_jobtemplates_crd.yaml has moved to config/crd/bases/tower.ansible.com_jobtemplates.yaml I noticed that the yaml file is markedly different.  Do I need to reinsert what I had in deploy/crds/tower.ansible.com_jobtemplates_crd.yaml as well as the other properties that are no longer there?

**Review by rooftopcellist — APPROVED** [review]
I just tested this out and am able to launch jobs and create JT's now.  Thanks @rh-dluong !

**Pull request merged**
